language: node_js
node_js:
 - 10.17.0
branches:
  only:
  - master
deploy:
  provider: elasticbeanstalk
  access_key_id: ${AWS_ACCESS_KEY_ID}
  secret_access_key: ${AWS_SECRET_ACCESS_KEY}
  region: us-east-1
  app: dbknews-elastic-beanstalk
  env: dbknews-salaryguide
  bucket_name: salaryguide.dbknews.com
  on:
    branch: master
after_deploy:
  - echo "Application Deployed!"
